name: CodeHaven CI/CD   

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  DOCKER_USERNAME: harsimranjit2004
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env: 
      DOCKER_REGISTRY: docker.io/${{env.DOCKER_USERNAME}}
    steps: 
      - name : Checkout Code
        uses: actions/checkout@v3

      - name: Set up docker 
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and Push Frontend Image
        working-directory: FrontEnd
        run: |
          docker build -t ${DOCKER_REGISTRY}/frontend:latest . 
          docker push ${DOCKER_REGISTRY}/frontend:latest
      
      - name: Build and Push Upload Service Image
        working-directory: Upload_Service
        run: |
          docker build -t ${DOCKER_REGISTRY}/upload-service:latest .
          docker push ${DOCKER_REGISTRY}/upload-service:latest
        
      - name: Build and Push Deployment Image
        working-directory: deploy-service
        run: | 
          docker build -t ${DOCKER_REGISTRY}/deployment:latest .
          docker push ${DOCKER_REGISTRY}/deployment:latest
      
      - name: Build and Push Request Handler Image
        working-directory: Request-Handler
        run: | 
          docker build -t ${DOCKER_REGISTRY}/request-handler:latest .
          docker push ${DOCKER_REGISTRY}/request-handler:latest
